image: reg.agria.pro:4567/docker/jdk13

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  TZ: "Europe/Moscow"
  GIT_STRATEGY: clone

before_script:
  - echo `pwd` # debug
  - echo "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" # debug
  - export GRADLE_USER_HOME="/cache/$CI_PROJECT_NAME/gradle"
build:
  stage: build
  script: ./gradlew clean classes
  cache:
    untracked: true

# прогоняем интеграционные тесты для postgres
test:
  stage: test
  script:
    - ./gradlew check
  cache:
    untracked: true
    policy: pull
  artifacts:
    name: "error_postgres_${CI_PROJECT_NAME}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: on_failure
    untracked: true
    expire_in: 1 day

#////////////////////////////////////////////////////////////////////////////////////
#Собираем артефакты для формирования образов
deploy_dev:
  stage: deploy
  image: reg.agria.pro:4567/docker/jdk13
  script:
    - ./gradlew assemble publish
  cache:
    untracked: true
    policy: pull
  artifacts:
    name: "jar_${CI_PROJECT_NAME}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - ./build/libs
    expire_in: 100 minute
  except:
    - /^prod/.*/

#Можем получить багу, тесты для одного а прогнали релиз для другого,
#так как в скрипте делаем pull, получается данны в ветке могут изменится
deploy_prod:
  stage: deploy
  image: reg.agria.pro:4567/docker/jdk13:jdkgit
  variables:
    CI_REPOSITORY_URL: git@dev.agria.pro:agri/proc.git
  #    CI_DEBUG_TRACE: "true"
  environment:
    name: $CI_BUILD_REF_NAME
  script:
    - git remote set-url origin https://$GIT_ACCESS_USER:$GIT_ACCESS_PASSWORD@dev.agria.pro/$CI_PROJECT_PATH.git
    - git config --global user.name $GIT_ACCESS_USER
    - git config --global user.email $GIT_ACCESS_EMAIL
    - git checkout $CI_BUILD_REF_NAME
    - git status
    - ./gradlew release -Prelease.useAutomaticVersion=true
  cache:
    untracked: true
    policy: pull
  artifacts:
    name: "jar_${CI_PROJECT_NAME}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - ./build/libs
    expire_in: 100 minute
  only:
    - /^prod/.*/