#spring.cloud.config.uri=http://${hostserver:localhost}:8888
server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  mvc:
    async:
      request-timeout: 35s
  application:
    name: serviceregistry

management.endpoint:
  metrics:
    enabled: true
    export.prometheus.enabled: true
  prometheus.enabled: true
